import { analyzeRound } from '@vital-fantasy/analyze-round';

const results = {
  // Elite Women
  'Vali Holl|Elite Women': { Rank: 1 },
  'Anna Newkirk|Elite Women': { Rank: 2 },
  'Tahnee Seagrave|Elite Women': { Rank: 3 },
  'Jess Blewitt|Elite Women': { Rank: 4 },
  'Eleonora Farina|Elite Women': { Rank: 5 },
  'Lisa Baumann|Elite Women': { Rank: 6 },
  'Monika Hrastnik|Elite Women': { Rank: 7 },
  'Myriam Nicole|Elite Women': { Rank: 8 },
  'Louise Ferguson|Elite Women': { Rank: 9 },
  'Mille Johnset|Elite Women': { Rank: 10 },
  // Protected
  'Nina Hoffmann|Elite Women': { Rank: 5 },
  'Camille Balanche|Elite Women': { Rank: 5 },
  'Marine Cabirou|Elite Women': { Rank: 5 },

  // Elite Men
  'Loic Bruni|Elite Men': { Rank: 1 },
  'Luca Shaw|Elite Men': { Rank: 2 },
  'Troy Brosnan|Elite Men': { Rank: 3 },
  'Oisin O’Callaghan|Elite Men': { Rank: 4 },
  'Amaury Pierron|Elite Men': { Rank: 5 },
  'Ronan Dunne|Elite Men': { Rank: 6 },
  'Loris Vergier|Elite Men': { Rank: 7 },
  'Dakotah Norton|Elite Men': { Rank: 8 },
  'Thibaut Daprela|Elite Men': { Rank: 9 },
  'Bernard Kerr|Elite Men': { Rank: 10 },
  'Henri Kiefer|Elite Men': { Rank: 11 },
  'Danny Hart|Elite Men': { Rank: 12 },
  'Andreas Kolb|Elite Men': { Rank: 13 },
  'Matt Walker|Elite Men': { Rank: 14 },
  'Remi Thirion|Elite Men': { Rank: 15 },
  'Lachlan Stevens-Mcnab|Elite Men': { Rank: 16 },
  'Max Hartenstern|Elite Men': { Rank: 17 },
  'Charlie Hatton|Elite Men': { Rank: 18 },
  'Jordan Williams|Elite Men': { Rank: 19 },
  "Kye A'Hern|Elite Men": { Rank: 20 },
  'Joe Breeden|Elite Men': { Rank: 21 },
  'Ryan Pinkerton|Elite Men': { Rank: 22 },
  'Bodhi Kuhn|Elite Men': { Rank: 23 },
  'Ollie Davis|Elite Men': { Rank: 24 },
  'Remy Meier-Smith|Elite Men': { Rank: 25 },
  'Loris Revelli|Elite Men': { Rank: 26 },
  'Antoine Pierron|Elite Men': { Rank: 27 },
  'Reece Wilson|Elite Men': { Rank: 28 },
  'Jakob Jewett|Elite Men': { Rank: 29 },
  'Greg Williamson|Elite Men': { Rank: 30 },
  // Protected
  'Finn Iles|Elite Men': { Rank: 5 },
  'Benoit Coulanges|Elite Men': { Rank: 5 },

  // Junior Women
  'Eliana Hulsebosch|Junior Women': { Rank: 1 },
  'Sacha Earnest|Junior Women': { Rank: 2 },
  'Erice Van Leuven|Junior Women': { Rank: 3 },
  'Ella Svegby|Junior Women': { Rank: 4 },
  'Heather Wilson|Junior Women': { Rank: 5 },
  'Amelia Dudek|Junior Women': { Rank: 6 },
  'Matilda Melton|Junior Women': { Rank: 7 },
  'Sacha Mills|Junior Women': { Rank: 8 },
  'Kale Cushman|Junior Women': { Rank: 9 },
  'Minu Stoffers|Junior Women': { Rank: 10 },

  // Junior Men
  'Asa Vermette|Junior Men': { Rank: 1 },
  'Dane Jewett|Junior Men': { Rank: 2 },
  'Mylann Falquet|Junior Men': { Rank: 3 },
  'Max Alran|Junior Men': { Rank: 4 },
  'Till Alran|Junior Men': { Rank: 5 },
  'Lucas Lagneau|Junior Men': { Rank: 6 },
  'Jon Mozell|Junior Men': { Rank: 7 },
  'Mike Huter|Junior Men': { Rank: 8 },
  'Luke Wayman|Junior Men': { Rank: 9 },
  'Rudi Eichhorn|Junior Men': { Rank: 10 },
  'Rory Meek|Junior Men': { Rank: 11 },
  'Lucas Dedora|Junior Men': { Rank: 12 },
  'Riko Maeuibo|Junior Men': { Rank: 13 },
  'Bode Burke|Junior Men': { Rank: 14 },
  'Clement Laugier|Junior Men': { Rank: 15 },
  'Roee Ostfeld|Junior Men': { Rank: 16 },
  'Ryan Griffith|Junior Men': { Rank: 17 },
  'Will Haines|Junior Men': { Rank: 18 },
  'Gavin Tomlinson|Junior Men': { Rank: 19 },
  'Lukas Lammlein|Junior Men': { Rank: 20 },
  'Julian Koch|Junior Men': { Rank: 21 },
  'Ryan Hastings|Junior Men': { Rank: 22 },
  'Raphael Giambi|Junior Men': { Rank: 23 },
  'Vincent Jouvenal|Junior Men': { Rank: 24 },
  'Rafael Pelletier|Junior Men': { Rank: 25 },
};

const statsCsvPath = 'apps/leogang/src/assets/Leogang Advanced Stats.csv';

await analyzeRound('Leogang', statsCsvPath, results);
